version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: fun_auth_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fun_root
      POSTGRES_DB: fun_auth_db
      POSTGRES_USER: fun_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - auth_network

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge
